version: '3.9'

services:

  db:
    image: neo4j:community
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ~/neo4j/data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aquacloud
      - MONGO_INITDB_ROOT_PASSWORD=aquacloud

  api:
    container_name: api
    image: spring-backend-interview-api-img
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    restart: always
